Added data-frames.adoc for data.frames page
TheDataMine/the-examples-book pull request #299
Opened 2022-01-19 22:40 UTC by lsukova

Moved the old Examples Book content to the new Examples Book, making minor revisions for flow. I was looking for a grep page to link on the final example, but I didn't see one in R base functions. Is it elsewhere or is that a page that still needs moved over?

2022-01-20 13:22 UTC, kevinamstutz commented
@lsukova you're on it! This is looking great. You can see a tiny bit of R-grep content from the old book [here](https://thedatamine.github.io/the-examples-book/r.html#r-grep), but it would need to be moved over and a new page added. I'll add it as a task to the project board and assign you to it here shortly.

Couple of notes:

1. Since you named the branch properly, the app that we use in the data mine to track work automatically moved the task to "in progress" for me, so thank you!: <img width="348" alt="Screen Shot 2022-01-20 at 07 17 41" src="https://user-images.githubusercontent.com/8942496/150346264-2707ec1d-0378-46ef-9fc6-3731fb24453d.png">
2. I'll review this as soon as I get a chance -- today is pretty packed for me.
3. When you go to work on another task on the project board, make sure to create a new branch and from the `main` branch with the same naming convention you used (with INS). To create a branch from the `main` branch you will need to first switch to the `main` branch in gh desktop and _then_ create a new branch (just FYI).
4. When you come back to this project to make requested changes, you can just switch branches in github desktop and make more changes and push them up and they will continue to be tracked here, so switching between and updating tasks is no problem (just in case that is something that worried you).

2022-01-20 13:26 UTC, kevinamstutz commented
@lsukova I added a new task #300

2022-01-21 18:39 UTC, kevinamstutz requested changes
Hey @lsukova sorry for the delay -- there will be times where a PR will sit there for a week, hope that is ok.

Here are some notes to please change:

- Remove the extra hash tags in the output (for example when doing head(df))
- Double check and change the coding language in the code blocks (for example, I see at least 1 `[source,python]` instead of `[source,r]`
- I'd surround your [TIP] content (and other like CAUTION, NOTE, etc.) with 4 equals, like this:
```
[TIP]
====
Though the row names replace the numerical indices in the output, we can still index using either. This same logic applies to columns, which also have intrinsic indices and are required to be named in order to be created.
====
```
- For numbered lists, it is best to use just a period with no number -- asciidoc will auto increment so we dont have to edit the entire list if we modify it down the road. So instead of:

```
1. item 1
2. item 2
```
Do

```
. item 1
. item 2
```
- Instead of italicizing the example/question text, use a level 4 header (4 equals signs) -- that way we can link to specific examples.
- Lastly, if you can think of a way to break down this page content into a couple sections/subsection with some headers that would be great. Then, maybe you can make Examples be level 3 (=== Examples) and the question texts be level 4 (==== This is a question). That would be awesome -- it is fine if there isn't a good way to do that.

This is quite a few notes but don't take it the wrong way -- this is awesome! Thank you thank you!

2022-01-24 05:15 UTC, lsukova commented
Hey Kevin -- I committed the changes to data-frames.adoc, but it didn't generate a new pull request. I'm assuming this is just because we're still on this original pull request (still getting used to GitHub), so I figured I'd comment here as well in case it didn't notify you.

2022-01-25 22:09 UTC, kevinamstutz commented
Hey @lsukova -- perfect! You can see when you make more changes to this branch they just appear right here in the PR -- exactly what we want. Thank you!

Okay, only a couple more changes (please):

- Could you please remove the italicize/bold on the example question text (remove the asterisks) -- the level 4 header does enough formatting for us.
- Could you add a newline after each header? 

After that I'm going to go ahead and merge this guy! Thank you thank you!

2022-03-08 18:29 UTC, naomim01 commented on content/modules/r/pages/data-frames.adoc
> +Data.frames are one of the primary data structures used very frequently when working in R. Data.frames are tabular data structures, consisting of named columns of equal size, where each column has a
Data.frames are one of the most frequently used when working in R. 

Data.Frames organize data into a 2D table, using rows and columns. 
Each column contains values of one variable and each row contains one set of values for each column.

2022-03-08 19:07 UTC, naomim01 commented on content/modules/r/pages/data-frames.adoc
> +The different columns of a data frame can be disparate in type, the only requirement is that values column-wide have the same type. In this case, `cat_1` and `cat_2` contain integers, `ok` contains b
The columns in a data.frame can be distinct/different, however, here is one requirement that each column contains the same type of values.

2022-03-08 19:27 UTC, naomim01 commented on content/modules/r/pages/data-frames.adoc
> +You can create a data.frame easily. Vectors are used to fill the columns as follows:
Creating a data.frame is easily done by filling in the columns using vectors.  (this would be a good place to explain what you are doing in the code)

2022-05-09 15:59 UTC, dglass19 commented
I believe Drew made all the changes required. Merging the PR.

2022-05-09 15:59 UTC, merged